# Generated by Django 2.2.10 on 2020-06-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_time',
            field=models.DateTimeField(default=None),
        ),
    ]
