# Generated by Django 2.2.10 on 2020-06-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200603_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
